### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/DevComic#1]
Add a CONTRIBUTING.md file similar too https://github.com/rajsubhankar/HumansOfGitHub/blob/master/CONTRIBUTING.md

For beginners.

**Comment by anubhakushwaha** [comment]
@raj-subhankar Can I work upon this?

**Comment by raj-subhankar** [comment]
Sure go ahead!

**Comment by anubhakushwaha** [comment]
@raj-subhankar #4 Done.
