### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/DevComic#2]
It's a simple one Activity app, open to suggestions for UI changes, feel free to get creative. Add screenshot of your changes.

**Comment by rrishabhj** [comment]
hey i am working on the issue.

**Comment by rrishabhj** [comment]
what is your app about?

**Comment by raj-subhankar** [comment]
It's a comic app.

**Comment by AggarwalAditya** [comment]
Can i work on this issue?

**Comment by YashishDua** [comment]
Can I take up this Issue ?

**Comment by raj-subhankar** [comment]
@AggarwalAditya @YashishDua hey sure, but please check out the cureent updates and let me know what changes you intend to make

**Comment by vjs3** [comment]
@raj-subhankar I saw that you have not closed this issue! Does this mean you still need some good design? If yes then let me know ASAP as very less time is left.
